### PR TITLE
Convert to Jekyll theme

### LINKED ISSUE #1: Converting this to Jekyll theme
This is very neat and slick theme. Many thanks for creating it! I have a few questions:

1. Are there any plans to convert this into a Jekyll theme ?
2. Any plans for having a page where we can show a list. 

If we can cater 2 above then this theme can be very well utilized for writing blog articles.
Thanks again!

### PR DESCRIPTION
**Pull request by guillermocalvo**
I refactored the theme so that it can be used with [Jekyll](https://jekyllrb.com/).
This makes it really easy using the theme in [GitHub Pages](https://pages.github.com/).

> [*LIVE DEMO*](https://leakyabstractions.github.io/pretty-docs/)

I would like to create a new branch `gh-pages` into this repository, but GitHub cannot create a pull request with a target branch that does not exist yet. Therefore I used `master` branch. Please feel free to modify this pull request if you want.

Resolves #1.

### CODE REVIEW

**Comment by Frotty** [comment]
Hey, this is pretty awesome @guillermocalvo 
It seems like the repository owner isn't active anymore, so I have but one request for you:

The theme is nice and working, but I find it rather sad that there are no anchors for headings in a doc-page.
This means you cannot send someone a link of a specific position inside the page, which might be very big.
I think this is my only major concern - is there an easy way you could implement this to your fork?

Kind Regards.

**Comment by guillermocalvo** [comment]
Hi @Frotty,

I don't exactly understand what kind of anchors are you missing there. The template currently generates anchors for all **sections**, and kramdown automatically generates IDs for all **headings**.

For example, you can try these links to the live demo:

- <https://leakyabstractions.github.io/PrettyDocs-Theme/license.html#prettydocs-credits> (the anchor `prettydocs-credits` is generated by the template)
- <https://leakyabstractions.github.io/PrettyDocs-Theme/license.html#cc-by-30> (the anchor `cc-by-30` is generated by kramdown)

Please let me know if those were the anchors you meant. If I got it all wrong, could you please provide me with an specific example of what you intend to achieve?

Regards.

**Comment by Frotty** [comment]
Hi, you are right, those are the anchors. I just noticed that you can rightclick the sidebar-links "copy link address" to get the anchor, but leftclick will not make it appear in the address bar of my browser (chrome).

I guess I would prefer it, if a leftclick also made the anchor appear.

**Comment by guillermocalvo** [comment]
Hey @Frotty, just made a small change to display anchors in the browser. Please check it out :+1: 

You are right about Prism, [I disabled it](https://github.com/xriley/PrettyDocs-Theme/pull/5/commits/33a96f63f317e34f9e96fcf5beda8d3ca445016d) because Jekyll has its own highlighter; I think it's better that way because the code is highlighted just once (server-side).

**Comment by Frotty** [comment]
Thanks for the patch 👍 

Maybe add a note about Prism. I disabled the default rogue highlighter with `highlighter: none` in config.yml to keep my custom highlighter for Prism.

**Pull request closed without merging**
